[package]
name = "webhooks"
version = "0.1.0"
edition = "2018"
description = "Webhook server"
authors = ["Victor Gorchilov <victor@gorchilov.com>"]
readme = "README.md"
repository = "https://github.com/ManiacMaxo/webhooks/"
license = "MIT"
keywords = ["webhooks"]
categories = ["web-programming::http-client", "filesystem"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"